<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Datadriven2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>34b6c84f-f198-480c-84d5-aa4a59515d10</testSuiteGuid>
   <testCaseLink>
      <guid>a5210baf-5c0c-46e5-84d2-a06033e37f6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data driven/loginmenu</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f3f8f787-861c-4ec9-8767-b3ddc2ebf5df</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data driven/logindata</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9697b3c2-d1bc-488a-b136-e454416f977e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data driven/logindata</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f3f8f787-861c-4ec9-8767-b3ddc2ebf5df</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>f78bc5da-ec83-42c5-982c-55780fa874ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f3f8f787-861c-4ec9-8767-b3ddc2ebf5df</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>f4523960-2e11-40b8-8a37-103e65374f53</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
